name: StrangeGuns
version: '${version}'
main: tundraclimate.com.github.strangeguns.StrangeGuns
api-version: 1.16
authors: [ Tundra_Climate ]
description: added Strange Guns

commands:
  strangegun:
    description: get StrangeGuns
