name: StorageGuns
version: '${version}'
main: tundraclimate.com.github.storageguns.StorageGuns
api-version: 1.16
authors: [ Tundra_Climate ]
description: added Storage Guns

commands:
  strangegun:
    description: get StrangeGuns
